version: '3'

services:
  backend:
    container_name: backend
    restart: always
    build: .
    working_dir: /backend
    volumes:
      - .:/backend
      - ./.zsh/.zshrc:/home/node/.zshrc
      - ./.zsh/.zsh_history:/home/node/.zsh_history
    networks:
      - node_network
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      - postgres

  postgres:
    container_name: db
    restart: always
    image: postgres:15.1
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_DB: 'customer_db'
    volumes:
      - 'customer_db:/var/lib/postgresql/data'
    networks:
      - node_network
    ports:
      - '5432:5432'

networks:
  node_network:
    driver: bridge

volumes:
  customer_db:
    driver: local
